# v1.00 _config.yml

title: "Snooey"
url: "https://snooey.com"
baseurl: "/"
title_seperator: " | "
locale: "en"
timezone: "Australia/Brisbane"
copyright: Copyright (c) 2018-2020 Shane Hoey

exclude:
    - LICENSE
    - README.md
    - .gitignore
    - Gemfile
    - Gemfile.lock

plugins_dir: _plugins
plugins:
    - jekyll-remote-theme
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-remote-theme

remote_theme: shanehoey/snooey

include:
    - _pages
    - _redirects

collections_dir: collections

collections:
    code:
        output: true
        permalink: /:collection/:path/
    documents:
        output: true
        permalink: /:collection/:path/
    snippets:
        output: true
        permalink: /:collection/:path/
    tldr:
        output: true
        permalink: /:collection/:path/
    tools:
        output: true
        permalink: /:collection/:path/
    videos:
        output: true
        permalink: /:collection/:path/
    wizards:
        output: true
        permalink: /:collection/:path/

defaults:
    - scope:
          path: ""
      values:
          title:
          subtitle:
          excerpt:
          description:
          author: Shane Hoey
          icon: fas fa-rocket
          navbar: true
          breadcrumb: true
          carousel: false
          footer: true
          theme:
          image:
              horizontal: https://source.unsplash.com/random/750x400
              vertical: https://source.unsplash.com/random/400x750
              square: https://source.unsplash.com/random/300x300
              random: https://source.unsplash.com/random/750x400
              background: https://source.unsplash.com/random/2400x1800
              profile: https://source.unsplash.com/random/300x450
    - scope:
          path: ""
          type: "pages"
      values:
          layout: "page"
          permalink: /:basename/
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
          permalink: /blogs/:slug/
    - scope:
          path: ""
          type: "code"
      values:
          layout: "code"
          theme: "code"
    - scope:
          path: ""
          type: "documents"
      values:
          layout: "documents"
          theme: "documents"
    - scope:
          path: ""
          type: "tools"
      values:
          layout:  tools
          theme:  tools
    - scope:
          path: ""
          type: "snippets"
      values:
          layout: "snippets"
          theme: "snippets"
    - scope:
          path: ""
          type: "tldr"
      values:
          layout: tldr
          theme: tldr
    - scope:
          path: ""
          type: "videos"
      values:
          layout: videos
          theme:  videos
    - scope:
          path: ""
          type: "wizards"
      values:
          layout: wizards
          theme: wizards
