# v1.00 _config.yml

#   DOCUMENTATION Add documentation

title: "Shane Hoey, Reinventing the Modern Workplace"
url: "https:/shanehoey.com"
baseurl: "/"
title_seperator: " | "
locale: "en"
timezone: "Australia/Brisbane"

exclude:
  - LICENSE
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock

plugins_dir:                _plugins
plugins:
  - jekyll-remote-theme

remote_theme:     shanehoey/snooey

include:
  - _pages

collections_dir: collections

collections:
  code:
    output: true
    permalink: /:collection/:path/
  documents:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  snippets:
    output: true
    permalink: /:collection/:path/
  tldr:
    output: true
    permalink: /:collection/:path/
  videos:
    output: true
    permalink: /:collection/:path/
  wizards:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
    values:
      title:
      subtitle:
      excerpt:
      description:
      author: Shane Hoey
      icon: fas fa-rocket
      navbar: true
      breadcrumb: true
      carousel: false
      footer: true
      pagetheme: default
      image:
        horizontal: https://source.unsplash.com/bepwY8khinw/750x400
        vertical: https://source.unsplash.com/bepwY8khinw/400x750
        square: https://source.unsplash.com/bepwY8khinw/300x300
        random: https://source.unsplash.com/bepwY8khinw/750x400
        background: https://source.unsplash.com/bepwY8khinw/2400x1800
        profile: https://source.unsplash.com/bepwY8khinw/300x450
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      permalink: /:basename/
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "code"
    values:
      layout: "code"
      pagetheme: code
  - scope:
      path: ""
      type: "documents"
    values:
      layout: "documents"
      pagetheme: documents
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "projects"
      pagetheme: projects
  - scope:
      path: ""
      type: "snippets"
    values:
      layout: "snippets"
  - scope:
      path: ""
      type: "tldr"
    values:
      layout: "tldr"
      pagetheme: tldr
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "videos"
      pagetheme: videos
  - scope:
      path: ""
      type: "wizards"
    values:
      layout: "wizards"
      pagetheme: wizards
