version: '3'

services:
    jekyll:
        image: jekyll/jekyll:latest
        command: jekyll serve --watch --force_polling --trace
        ports:
            - 82:4000
        volumes:
            - .:/srv/jekyll